WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCOUNTER
	WHERE
	    ENCOUNTER.ENCNTR_ID IN @prompt('Enter value(s) for Encntr ID','A',,Multi,Free,Persistent,,User:0)
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID,
	ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID,
	PRSNL.NAME_FULL_FORMATTED AS ATTENDING,
	pi_get_cv_display(PRSNL.POSITION_CD) AS PROVIDER_POSITION,
	pi_from_gmt(ENCNTR_PRSNL_RELTN.BEG_EFFECTIVE_DT_TM, 'America/Chicago') AS BEGIN_DATETIME,
	pi_from_gmt(ENCNTR_PRSNL_RELTN.END_EFFECTIVE_DT_TM, 'America/Chicago') AS END_DATETIME,
	pi_from_gmt(ENCNTR_PRSNL_RELTN.TRANSACTION_DT_TM, 'America/Chicago') AS TRANSACT_DATETIME
FROM
	ENCNTR_PRSNL_RELTN,
	PATIENTS,
	PRSNL
WHERE
	PATIENTS.ENCNTR_ID = ENCNTR_PRSNL_RELTN.ENCNTR_ID
	AND ENCNTR_PRSNL_RELTN.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
	AND ENCNTR_PRSNL_RELTN.ACTIVE_IND = 1
	AND ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID = PRSNL.PERSON_ID
