WITH DOSES AS (
    SELECT DISTINCT
        CLINICAL_EVENT.ENCNTR_ID,
        CLINICAL_EVENT.PERSON_ID,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS MED_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		CE_MED_RESULT.ADMIN_DOSAGE AS DOSE,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSE_UNIT,
		-- CE_MED_RESULT.INFUSION_RATE AS RATE,
		-- pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS RATE_UNIT,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ROUTE,
		-- pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
    FROM
        CE_MED_RESULT,
        CLINICAL_EVENT,
        ENCNTR_LOC_HIST,
		ORDERS
    WHERE
        CLINICAL_EVENT.EVENT_CD IN (
			37557204, -- HYDROmorphone
			37557620, -- morphine Sulfate	
			37557746 --OXYcodone			
		)
        AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'11/01/2021 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'12/01/2021 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			) - 1/86400
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
    	AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.ADMIN_DOSAGE > 0
    	AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
    	AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
    	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
    	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
    		SELECT MAX(ELH.TRANSACTION_DT_TM)
    		FROM ENCNTR_LOC_HIST ELH
    		WHERE
    			CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
    			AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
    	)
/* 		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3821 -- HH Clinics		
		) */
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
			1233772, -- HH PACU
			43683126, -- HH AMSA
			43683728, -- HH DSU
			240867995, -- HH APAC
			3245580207, -- HH S AMSA
			9763063 -- HH PAHH
		)
    	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
        AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
)

SELECT 
	DOSES.*,
	ORDERS.ORDER_MNEMONIC,
	ORDER_PRODUCT.ITEM_ID,
	MED_IDENTIFIER.VALUE AS MED_PRODUCT,
	pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
	PATHWAY_CATALOG.DESCRIPTION AS ORDER_FROM_MPP,
	ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS WEIGHT,
	OD_WT_UNITS.OE_FIELD_DISPLAY_VALUE AS WEIGHT_UNITS
FROM
	DOSES,
	MED_IDENTIFIER,
	ORDER_DETAIL,
	ORDER_DETAIL OD_WT_UNITS,
	ORDER_PRODUCT,
	ORDERS,
	PATHWAY_CATALOG
WHERE
	DOSES.ORIG_ORDER_ID = ORDERS.ORDER_ID
	AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID(+)
	AND ORDER_DETAIL.OE_FIELD_MEANING_ID(+) = 99 -- WEIGHT
	AND ORDER_DETAIL.ACTION_SEQUENCE(+) = 1
	AND ORDERS.ORDER_ID = OD_WT_UNITS.ORDER_ID(+)
	AND OD_WT_UNITS.OE_FIELD_MEANING_ID(+) = 100 -- WEIGHTUNIT
	AND OD_WT_UNITS.ACTION_SEQUENCE(+) = 1
	AND ORDERS.PATHWAY_CATALOG_ID = PATHWAY_CATALOG.PATHWAY_CATALOG_ID
	AND PATHWAY_CATALOG.PATHWAY_CATALOG_ID = 1901565469 -- Anesthesia Post-OP PACU MPP
	AND ORDERS.ORDER_ID = ORDER_PRODUCT.ORDER_ID(+)
	AND ORDER_PRODUCT.INGRED_SEQUENCE(+) = 1
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID(+)
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD(+) = 1564 -- Description
	AND MED_IDENTIFIER.MED_PRODUCT_ID(+) = 0
	AND MED_IDENTIFIER.PRIMARY_IND(+) = 1