WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		LOWER(pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)) AS MEDICATION,
		CE_MED_RESULT.ADMIN_DOSAGE,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ADMIN_ROUTE,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_FACILITY_CD) AS FACILITY,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		pi_get_cv_display(ENCNTR_LOC_HIST.MED_SERVICE_CD) AS MED_SERVICE,
		pi_get_cv_display(ENCNTR_LOC_HIST.ENCNTR_TYPE_CD) AS ENCNTR_TYPE,
		PRSNL.NAME_FULL_FORMATTED AS ATTENDING
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_ALIAS,
		ENCNTR_LOC_HIST,
		ENCNTR_PRSNL_RELTN,
		PRSNL
	WHERE
		CLINICAL_EVENT.EVENT_CD = 300078694 -- alvimopan
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'03/01/2019 00:00:00'}, User:1),
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				),
				pi_time_zone(1, 'America/Chicago')
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'04/01/2020 00:00:00'}, User:2),
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400,
				pi_time_zone(1, 'America/Chicago')
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823, -- HH Rehab
			1099966301 -- HH Oncology TMC
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_PRSNL_RELTN.ENCNTR_ID
		AND ENCNTR_PRSNL_RELTN.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
		AND ENCNTR_PRSNL_RELTN.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN ENCNTR_PRSNL_RELTN.BEG_EFFECTIVE_DT_TM AND ENCNTR_PRSNL_RELTN.END_EFFECTIVE_DT_TM
		AND ENCNTR_PRSNL_RELTN.TRANSACTION_DT_TM = (
				SELECT MAX(EPR.TRANSACTION_DT_TM)
				FROM ENCNTR_PRSNL_RELTN EPR
				WHERE EPR.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND CLINICAL_EVENT.ENCNTR_ID = EPR.ENCNTR_ID
				AND EPR.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
		)
		AND ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID = PRSNL.PERSON_ID
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
), SURG_TIMES AS (
	SELECT DISTINCT
		DOSES.ENCNTR_ID,
		SURGICAL_CASE.SURG_CASE_ID,
		SURGICAL_CASE.SURG_START_DT_TM,
		SURGICAL_CASE.SURG_STOP_DT_TM,
		CT_ANESTH_START.CASE_TIME_DT_TM AS ANESTH_START_DT_TM,
		CT_ANESTH_STOP.CASE_TIME_DT_TM AS ANESTH_STOP_DT_TM,
		CASE SURG_CASE_PROCEDURE.PRIMARY_PROC_IND
			WHEN 1 THEN 'TRUE'
			ELSE 'FALSE'
		END AS PRIMARY_PROCEDURE,
		pi_get_cv_display(SURG_CASE_PROCEDURE.SURG_PROC_CD) AS SURGERY
	FROM
		CASE_TIMES CT_ANESTH_START,
		CASE_TIMES CT_ANESTH_STOP,
		DOSES,
		SURGICAL_CASE,
		SURG_CASE_PROCEDURE
	WHERE
		DOSES.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID
		AND SURGICAL_CASE.SURG_CASE_ID = SURG_CASE_PROCEDURE.SURG_CASE_ID
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_START.SURG_CASE_ID
		AND CT_ANESTH_START.TASK_ASSAY_CD = 10511932 -- SN - CTm - Anesthesia - Start Time
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_STOP.SURG_CASE_ID
		AND CT_ANESTH_STOP.TASK_ASSAY_CD = 10511933 -- SN - CTm - Anesthesia - Stop Time
), ICD_PROC AS (
	SELECT DISTINCT
		DOSES.ENCNTR_ID,
		NOMENCLATURE.SOURCE_IDENTIFIER AS PROCEDURE_CODE,
		NOMENCLATURE.SOURCE_STRING AS PROCEDURE,
		pi_from_gmt(PROCEDURE.PROC_DT_TM, 'America/Chicago') AS PROCEDURE_DATETIME
	FROM
		DOSES,
		NOMENCLATURE,
		PROCEDURE
	WHERE
		DOSES.ENCNTR_ID = PROCEDURE.ENCNTR_ID
		AND PROCEDURE.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836522 -- ICD-10-PCS
)

SELECT * FROM DOSES
-- SELECT * FROM SURG_TIMES
-- SELECT * FROM ICD_PROC