WITH DSU_PTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.REG_DT_TM,
		ENCOUNTER.DISCH_DT_TM,
		ENCOUNTER.ENCNTR_TYPE_CLASS_CD,
		ENCOUNTER.LOC_NURSE_UNIT_CD
	FROM
		ENCNTR_LOC_HIST,
		ENCOUNTER
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2020 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'3/01/2021 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'America/Chicago'
			)
		AND ENCOUNTER.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 43683728 -- HH DSU
), APAP_ORDERS AS(
	SELECT DISTINCT
		DSU_PTS.ENCNTR_ID,
		ORDERS.ORDER_ID,
		ORDERS.TEMPLATE_ORDER_ID,
		ORDERS.ORIG_ORDER_DT_TM,
		-- ORDERS.TEMPLATE_ORDER_FLAG,
		ORDERS.ORIG_ORD_AS_FLAG,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS ROUTE,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD
	FROM
		DSU_PTS,
		ENCNTR_LOC_HIST,
		ORDER_DETAIL,
		ORDERS
	WHERE
		DSU_PTS.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND DSU_PTS.PERSON_ID = ORDERS.PERSON_ID
		AND ORDERS.CATALOG_CD = 9902878 -- acetaminophen
		AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
		AND ORDERS.TEMPLATE_ORDER_FLAG IN (0, 1)
		AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID
		AND ORDER_DETAIL.OE_FIELD_MEANING_ID = 2050 -- RXROUTE
		AND ORDERS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				ORDERS.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= ORDERS.ORIG_ORDER_DT_TM
), SURG_TIMES AS (
	SELECT DISTINCT
		DSU_PTS.ENCNTR_ID,
		SURGICAL_CASE.SURG_CASE_ID,
		SURGICAL_CASE.SURG_START_DT_TM,
		SURGICAL_CASE.SURG_STOP_DT_TM,
		SURG_CASE_PROCEDURE.SURG_PROC_CD,
		CT_ANESTH_START.CASE_TIME_DT_TM AS ANESTH_START_DT_TM,
		CT_ANESTH_STOP.CASE_TIME_DT_TM AS ANESTH_STOP_DT_TM
	FROM
		CASE_TIMES CT_ANESTH_START,
		CASE_TIMES CT_ANESTH_STOP,
		DSU_PTS,
		SURGICAL_CASE,
		SURG_CASE_PROCEDURE
	WHERE
		DSU_PTS.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID
		AND SURGICAL_CASE.SURG_CASE_ID = SURG_CASE_PROCEDURE.SURG_CASE_ID
		AND SURG_CASE_PROCEDURE.PRIMARY_PROC_IND = 1
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_START.SURG_CASE_ID(+)
		AND CT_ANESTH_START.TASK_ASSAY_CD(+) = 10511932 -- SN - CTm - Anesthesia - Start Time
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_STOP.SURG_CASE_ID(+)
		AND CT_ANESTH_STOP.TASK_ASSAY_CD(+) = 10511933 -- SN - CTm - Anesthesia - Stop Time
), APAP_DOSES AS (
	SELECT DISTINCT
		DSU_PTS.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		CLINICAL_EVENT.EVENT_ID,
		CASE 
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD
		-- CLINICAL_EVENT.ORDER_ID,
		-- CE_MED_RESULT.ADMIN_DOSAGE,
		-- CE_MED_RESULT.ADMIN_ROUTE_CD,
		-- pi_get_cv_display(MED_ADMIN_EVENT.EVENT_TYPE_CD) AS EVENT_TYPE
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		DSU_PTS,
		ENCNTR_LOC_HIST,
		ORDERS
	WHERE
		DSU_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND DSU_PTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD = 37556009 -- acetaminophen
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2020 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'3/01/2021 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'America/Chicago'
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CE_MED_RESULT.ADMIN_DOSAGE > 0
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		-- AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 43683728 -- HH DSU 
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID 
)

SELECT 
	DSU_PTS.ENCNTR_ID,
	pi_from_gmt(DSU_PTS.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
	pi_from_gmt(DSU_PTS.DISCH_DT_TM, 'America/Chicago') AS DISCH_DATETIME,
	pi_get_cv_display(DSU_PTS.ENCNTR_TYPE_CLASS_CD) AS ENCNTR_TYPE_CLASS,
	pi_get_cv_display(DSU_PTS.LOC_NURSE_UNIT_CD) AS DISCH_NURSE_UNIT,
	SURG_TIMES.SURG_CASE_ID,
	pi_get_cv_display(SURG_TIMES.SURG_PROC_CD) AS SURGERY,
	pi_from_gmt(SURG_TIMES.SURG_START_DT_TM, 'America/Chicago') AS SURG_START_DATETIME,
	pi_from_gmt(SURG_TIMES.SURG_STOP_DT_TM, 'America/Chicago') AS SURG_STOP_DATETIME,
	pi_from_gmt(SURG_TIMES.ANESTH_START_DT_TM, 'America/Chicago') AS ANESTH_START_DATETIME,
	pi_from_gmt(SURG_TIMES.ANESTH_STOP_DT_TM, 'America/Chicago') AS ANESTH_STOP_DATETIME,
	APAP_ORDERS.ORDER_ID,
	pi_from_gmt(APAP_ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
	APAP_ORDERS.ROUTE AS ORDER_ROUTE,
	pi_get_cv_display(APAP_ORDERS.LOC_NURSE_UNIT_CD) AS ORDER_NURSE_UNIT,
	pi_from_gmt(APAP_DOSES.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
	TRUNC(pi_from_gmt(APAP_DOSES.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS DOSE_MONTH,
	APAP_DOSES.EVENT_ID,
	-- pi_get_cv_display(APAP_DOSES.ADMIN_ROUTE_CD) AS ADMIN_ROUTE,
	pi_get_cv_display(APAP_DOSES.LOC_NURSE_UNIT_CD) AS ADMIN_NURSE_UNIT	
FROM 
	APAP_DOSES,
	APAP_ORDERS,
	DSU_PTS,
	SURG_TIMES
WHERE
	DSU_PTS.ENCNTR_ID = APAP_ORDERS.ENCNTR_ID
	AND APAP_ORDERS.ORIG_ORD_AS_FLAG = 0
	AND APAP_ORDERS.ENCNTR_ID = SURG_TIMES.ENCNTR_ID
	AND APAP_ORDERS.ENCNTR_ID = APAP_DOSES.ENCNTR_ID(+)
	AND APAP_ORDERS.ORDER_ID = APAP_DOSES.ORIG_ORDER_ID(+)