WITH DSU_PTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.REG_DT_TM,
		ENCOUNTER.DISCH_DT_TM,
		pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CLASS_CD) AS ENCNTR_TYPE_CLASS
	FROM
		ENCNTR_LOC_HIST,
		ENCOUNTER
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN
			pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -6), 'MONTH'), 'America/Chicago')
			AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, 'America/Chicago')
		AND ENCOUNTER.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 43683728 -- HH DSU
), SURG_TIMES AS (
	SELECT DISTINCT
		DSU_PTS.ENCNTR_ID,
		SURGICAL_CASE.SURG_CASE_ID,
		pi_get_cv_display(SURG_CASE_PROCEDURE.SURG_PROC_CD) AS SURGERY,
		SURGICAL_CASE.SURG_START_DT_TM,
		SURGICAL_CASE.SURG_STOP_DT_TM,
		CT_ANESTH_START.CASE_TIME_DT_TM AS ANESTH_START_DT_TM,
		CT_ANESTH_STOP.CASE_TIME_DT_TM AS ANESTH_STOP_DT_TM
	FROM
		CASE_TIMES CT_ANESTH_START,
		CASE_TIMES CT_ANESTH_STOP,
		DSU_PTS,
		SURGICAL_CASE,
		SURG_CASE_PROCEDURE
	WHERE
		DSU_PTS.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID
		AND SURGICAL_CASE.SURG_CASE_ID = SURG_CASE_PROCEDURE.SURG_CASE_ID
		AND SURG_CASE_PROCEDURE.PRIMARY_PROC_IND = 1
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_START.SURG_CASE_ID
		AND CT_ANESTH_START.TASK_ASSAY_CD = 10511932 -- SN - CTm - Anesthesia - Start Time
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_STOP.SURG_CASE_ID
		AND CT_ANESTH_STOP.TASK_ASSAY_CD = 10511933 -- SN - CTm - Anesthesia - Stop Time
), APAP_ORDERS AS(
	SELECT DISTINCT
		DSU_PTS.ENCNTR_ID,
		ORDERS.ORDER_ID,
		ORDERS.TEMPLATE_ORDER_ID,
		ORDERS.ORIG_ORDER_DT_TM,
		ORDERS.TEMPLATE_ORDER_FLAG,
		ORDERS.ORIG_ORD_AS_FLAG,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS ROUTE
	FROM
		DSU_PTS,
		ORDER_DETAIL,
		ORDERS
	WHERE
		DSU_PTS.PERSON_ID = ORDERS.PERSON_ID
		AND DSU_PTS.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND ORDERS.CATALOG_CD = 9902878 -- acetaminophen
		AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
		AND ORDERS.TEMPLATE_ORDER_FLAG IN (0, 1)
		AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID
		AND ORDER_DETAIL.OE_FIELD_MEANING_ID = 2050 -- RXROUTE
/* ), APAP_DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS DOSE_MONTH,
		CLINICAL_EVENT.EVENT_ID,
		ORDERS.TEMPLATE_ORDER_ID,
		CLINICAL_EVENT.ORDER_ID,
		-- CE_MED_RESULT.ADMIN_DOSAGE,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ADMIN_ROUTE
		-- pi_get_cv_display(MED_ADMIN_EVENT.EVENT_TYPE_CD) AS EVENT_TYPE
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37556009 -- acetaminophen
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -6), 'MONTH'), 'America/Chicago')
			AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, 'America/Chicago')
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CE_MED_RESULT.ADMIN_DOSAGE > 0
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 43683728 -- HH DSU
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID */
)

SELECT
	DSU_PTS.ENCNTR_ID,
	DSU_PTS.ENCNTR_TYPE_CLASS,
	APAP_ORDERS.TEMPLATE_ORDER_ID,
	APAP_ORDERS.ORDER_ID,
	pi_from_gmt(APAP_ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
	TRUNC(pi_from_gmt(APAP_ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago'), 'MONTH') AS ORDER_MONTH,
	pi_from_gmt(DSU_PTS.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
	pi_from_gmt(DSU_PTS.DISCH_DT_TM, 'America/Chicago') AS DISCH_DATETIME,
	SURG_TIMES.SURG_CASE_ID,
	SURG_TIMES.SURGERY,
	pi_from_gmt(SURG_TIMES.ANESTH_START_DT_TM, 'America/Chicago') AS ANESTH_START_DATETIME,
	pi_from_gmt(SURG_TIMES.ANESTH_STOP_DT_TM, 'America/Chicago') AS ANESTH_STOP_DATETIME,
	APAP_ORDERS.ROUTE
	-- pi_from_gmt(APAP_DOSES.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
	-- APAP_DOSES.EVENT_ID,
	-- APAP_DOSES.ADMIN_ROUTE
	/* CASE
		WHEN APAP_ORDERS.ORIG_ORDER_DT_TM < DSU_PTS.REG_DT_TM THEN 1
		ELSE 0
	END AS ORDER_PRIOR,
	CASE
		WHEN APAP_ORDERS.ORIG_ORDER_DT_TM < SURG_TIMES.ANESTH_START_DT_TM THEN 1
		ELSE 0
	END AS ORDER_BEFORE,
	CASE
		WHEN APAP_DOSES.EVENT_END_DT_TM < SURG_TIMES.ANESTH_START_DT_TM THEN 1
		ELSE 0
	END AS GIVEN_BEFORE,
	CASE
		WHEN APAP_DOSES.EVENT_END_DT_TM BETWEEN SURG_TIMES.ANESTH_START_DT_TM AND SURG_TIMES.ANESTH_STOP_DT_TM THEN 1
		ELSE 0
	END AS GIVEN_DURING	 */
FROM
	-- APAP_DOSES,
	APAP_ORDERS,
	DSU_PTS,
	SURG_TIMES
WHERE
	DSU_PTS.ENCNTR_ID = SURG_TIMES.ENCNTR_ID
	AND DSU_PTS.ENCNTR_ID = APAP_ORDERS.ENCNTR_ID
	-- AND APAP_ORDERS.ORIG_ORDER_DT_TM < SURG_TIMES.ANESTH_STOP_DT_TM
	-- AND APAP_ORDERS.ROUTE <> 'PYXIS'
	-- AND APAP_ORDERS.ORIG_ORD_AS_FLAG = 0
	-- AND APAP_ORDERS.ENCNTR_ID = APAP_DOSES.ENCNTR_ID(+)
	-- AND APAP_ORDERS.ORDER_ID = APAP_DOSES.ORDER_ID(+)
