SELECT DISTINCT
	ENCOUNTER.ENCNTR_ID,
	ENCOUNTER.PERSON_ID,
	ENCOUNTER.REG_DT_TM,
	pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
	ENCOUNTER.DISCH_DT_TM,
	pi_from_gmt(ENCOUNTER.DISCH_DT_TM, 'America/Chicago') AS DISCH_DATETIME,
	pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CLASS_CD) AS ENCNTR_TYPE_CLASS
FROM
	ENCNTR_LOC_HIST,
	ENCOUNTER
WHERE
	ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
	AND ENCOUNTER.REG_DT_TM BETWEEN
		pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -6), 'MONTH'), 'America/Chicago')
		AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, 'America/Chicago')
	AND ENCOUNTER.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 43683728 -- HH DSU