WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		CE_MED_RESULT.ADMIN_DOSAGE,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ROUTE
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37557647 -- naloxone
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'08/01/2021 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'06/01/2022 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'America/Chicago'
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		-- AND CE_MED_RESULT.ADMIN_DOSAGE > 0
		AND CE_MED_RESULT.ADMIN_ROUTE_CD IN (
			508984, -- IV
			9022513, -- INJ
			9022647, -- IVPB
			9022649 -- IVP	
		)
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND ELH.ACTIVE_IND = 1
		)
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3822, -- HH Trans Care
			3823 -- HH Rehab			
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND =1
), BP_PRIOR AS (
	SELECT DISTINCT
		DOSES.ENCNTR_ID,
		pi_from_gmt(DOSES.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		MAX(CLINICAL_EVENT.RESULT_VAL) KEEP (DENSE_RANK LAST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM, CLINICAL_EVENT.EVENT_ID) OVER (PARTITION BY DOSES.ENCNTR_ID, DOSES.EVENT_END_DT_TM) AS SBP_BASELINE
	FROM
		CLINICAL_EVENT,
		DOSES
	WHERE
		DOSES.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD  = 159 -- NUM
		AND DOSES.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			30098, -- Systolic Blood Pressure
			134401648 -- Arterial Systolic BP 1
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM < DOSES.EVENT_END_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
), BP_VALS AS (
	SELECT DISTINCT
		DOSES.ENCNTR_ID,
		pi_from_gmt(DOSES.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		DOSES.MEDICATION,
		DOSES.ADMIN_DOSAGE,
		DOSES.ROUTE,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS BP_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.RESULT_VAL
	FROM
		CLINICAL_EVENT,
		DOSES
	WHERE
		DOSES.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD  = 159 -- NUM
		AND DOSES.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			30098, -- Systolic Blood Pressure
			134401648 -- Arterial Systolic BP 1
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN DOSES.EVENT_END_DT_TM AND DOSES.EVENT_END_DT_TM + 1/48
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
)

SELECT 
	ENCNTR_ALIAS.ALIAS AS FIN,
	BP_VALS.*,
	BP_PRIOR.SBP_BASELINE
FROM 
	BP_PRIOR,
	BP_VALS,
	ENCNTR_ALIAS
WHERE
	BP_VALS.ENCNTR_ID = BP_PRIOR.ENCNTR_ID
	AND BP_VALS.DOSE_DATETIME = BP_PRIOR.DOSE_DATETIME
	AND BP_VALS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1