WITH DC_RX AS (
	SELECT DISTINCT
		ORDERS.ORDER_ID,
		ENCOUNTER.ENCNTR_ID,
		ORDERS.CATALOG_CD,
		ORDERS.ORDERED_AS_MNEMONIC,
		ORDERS.ORIG_ORDER_DT_TM,
		ENCOUNTER.LOC_FACILITY_CD,
		ENCOUNTER.LOC_NURSE_UNIT_CD,
		ENCOUNTER.MED_SERVICE_CD,
		ENCOUNTER.ENCNTR_TYPE_CLASS_CD,
		PRSNL.NAME_FULL_FORMATTED,
		PRSNL.POSITION_CD,
		FREQUENCY_SCHEDULE.FREQUENCY_CD,
		ORDERS.PRN_IND
	FROM
		ENCOUNTER,
		FREQUENCY_SCHEDULE,
		ORDER_ACTION,
		ORDERS,
		PI_THERA_CLASS_VIEW,
		PRSNL
	WHERE
		PI_THERA_CLASS_VIEW.DRUG_CAT IN ('narcotic analgesic combinations', 'narcotic analgesics')
		AND PI_THERA_CLASS_VIEW.DRUG_CAT_CD = ORDERS.CATALOG_CD
		AND ORDERS.CATALOG_CD NOT IN (
			9909955, -- belladonna-opium
			9909879, -- APAP/butalbital/caffeine/codeine
			9909887 -- ASA/butalbital/caffeine/codeine
		)
		AND ORDERS.ORIG_ORDER_DT_TM BETWEEN
			pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), pi_time_zone(2, @Variable('BOUSER'))) 
			AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
		AND ORDERS.ORIG_ORD_AS_FLAG = 1 -- Prescription/Discharge Order
		AND ORDERS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab
		)
		AND ORDERS.ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_TYPE_CD = 1376 -- Order
		AND ORDER_ACTION.ORDER_PROVIDER_ID = PRSNL.PERSON_ID
		AND ORDERS.FREQUENCY_ID = FREQUENCY_SCHEDULE.FREQUENCY_ID
), LAST_RX AS (
	SELECT DISTINCT
		MAX(DC_RX.ORDER_ID) AS ORDER_ID,
		DC_RX.ENCNTR_ID,
		DC_RX.CATALOG_CD,
		MAX(DC_RX.ORDERED_AS_MNEMONIC) KEEP (DENSE_RANK LAST ORDER BY DC_RX.ORDER_ID) AS ORDERED_AS_MNEMONIC,
		MAX(DC_RX.ORIG_ORDER_DT_TM) AS ORIG_ORDER_DT_TM,
		DC_RX.LOC_FACILITY_CD,
		DC_RX.LOC_NURSE_UNIT_CD,
		DC_RX.MED_SERVICE_CD,
		DC_RX.ENCNTR_TYPE_CLASS_CD,
		MAX(DC_RX.NAME_FULL_FORMATTED) KEEP (DENSE_RANK LAST ORDER BY DC_RX.ORDER_ID) AS NAME_FULL_FORMATTED,
		MAX(DC_RX.POSITION_CD) KEEP (DENSE_RANK LAST ORDER BY DC_RX.ORDER_ID) AS POSITION_CD,
		MAX(DC_RX.FREQUENCY_CD) KEEP (DENSE_RANK LAST ORDER BY DC_RX.ORDER_ID) AS FREQUENCY_CD,
		MAX(DC_RX.PRN_IND) KEEP (DENSE_RANK LAST ORDER BY DC_RX.ORDER_ID) AS PRN_IND
	FROM
		DC_RX
	GROUP BY
		DC_RX.ENCNTR_ID,
		DC_RX.CATALOG_CD,
		DC_RX.LOC_FACILITY_CD,
		DC_RX.LOC_NURSE_UNIT_CD,
		DC_RX.MED_SERVICE_CD,
		DC_RX.ENCNTR_TYPE_CLASS_CD		
), ORD_DETAILS AS (
	SELECT DISTINCT
		ORDER_DETAIL.ORDER_ID,
		ORDER_DETAIL.OE_FIELD_MEANING,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE
	FROM
		LAST_RX,
		ORDER_DETAIL
	WHERE
		LAST_RX.ORDER_ID = ORDER_DETAIL.ORDER_ID
		AND ORDER_DETAIL.ACTION_SEQUENCE = 1
), ORD_DETAIL_PIVOT AS (
	SELECT * FROM ORD_DETAILS
	PIVOT(
		MIN(OE_FIELD_DISPLAY_VALUE) FOR OE_FIELD_MEANING IN (
			'DISPENSEQTY' AS DISPENSE_QTY,
			'DISPENSEQTYUNIT' AS DISPENSE_UNIT,
			'DURATION' AS DURATION,
			'DURATIONUNIT' AS DURATION_UNIT,
			'FREETXTDOSE' AS FREETXT_DOSE,
			'PRNINSTRUCTIONS' AS PRN_INSTR,
			'NBRREFILLS' AS REFILLS,
			'RXROUTE' AS ROUTE,
			'SPECINX' AS SPECIAL_INSTR,
			'STRENGTHDOSE' AS DOSE,
			'STRENGTHDOSEUNIT' AS DOSE_UNIT,
			'VOLUMEDOSE' AS VOLUME,
			'VOLUMEDOSEUNIT' AS VOLUME_UNIT
		)
	)
)

SELECT DISTINCT
	LAST_RX.ORDER_ID,
	pi_from_gmt(LAST_RX.ORIG_ORDER_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS ORDER_DATETIME,
	TRUNC(pi_from_gmt(LAST_RX.ORIG_ORDER_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'MONTH') AS ORDER_MONTH,
	LAST_RX.ENCNTR_ID,
	pi_get_cv_display(LAST_RX.CATALOG_CD) AS MEDICATION,
	LAST_RX.ORDERED_AS_MNEMONIC AS ORDERED_AS,
	TO_NUMBER(ORD_DETAIL_PIVOT.DOSE) AS DOSE,
	ORD_DETAIL_PIVOT.DOSE_UNIT AS DOSE_UNIT,
	TO_NUMBER(ORD_DETAIL_PIVOT.VOLUME) AS VOLUME,
	ORD_DETAIL_PIVOT.VOLUME_UNIT AS VOLUME_UNIT,
	ORD_DETAIL_PIVOT.FREETXT_DOSE AS FREETXT_DOSE,
	ORD_DETAIL_PIVOT.ROUTE AS ROUTE,
	pi_get_cv_display(LAST_RX.FREQUENCY_CD) AS FREQ,
	CASE LAST_RX.PRN_IND
		WHEN 1 THEN 'PRN'
		ELSE 'Scheduled'
	END AS PRN,
	ORD_DETAIL_PIVOT.PRN_INSTR AS PRN_INSTR,
	ORD_DETAIL_PIVOT.SPECIAL_INSTR AS SPECIAL_INSTR,
	TO_NUMBER(ORD_DETAIL_PIVOT.DISPENSE_QTY) AS DISPENSE_QTY,
	ORD_DETAIL_PIVOT.DISPENSE_UNIT AS DISPENSE_UNIT,
	TO_NUMBER(ORD_DETAIL_PIVOT.DURATION) AS DURATION,
	ORD_DETAIL_PIVOT.DURATION_UNIT AS DURATION_UNIT,
	TO_NUMBER(ORD_DETAIL_PIVOT.REFILLS) AS REFILLS,
	LAST_RX.NAME_FULL_FORMATTED AS PROVIDER,
	pi_get_cv_display(LAST_RX.POSITION_CD) AS PROVIDER_POSITION,
	pi_get_cv_display(LAST_RX.MED_SERVICE_CD) AS MED_SERVICE,
	pi_get_cv_display(LAST_RX.LOC_FACILITY_CD) AS FACILITY,
	pi_get_cv_display(LAST_RX.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	pi_get_cv_display(LAST_RX.ENCNTR_TYPE_CLASS_CD) AS ENCNTR_TYPE
FROM
	LAST_RX,
	ORD_DETAIL_PIVOT
WHERE
	LAST_RX.ORDER_ID = ORD_DETAIL_PIVOT.ORDER_ID(+)
