SELECT DISTINCT
	ORDERS.ORDER_ID,
	ENCOUNTER.ENCNTR_ID,
	--ENCOUNTER.PERSON_ID,
	pi_get_cv_display(ORDERS.CATALOG_CD) AS MEDICATION,
	ORDERS.ORDERED_AS_MNEMONIC,
	ORDERS.ORIG_ORDER_DT_TM,
	pi_get_cv_display(ENCOUNTER.LOC_FACILITY_CD) AS FACILITY,
	pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	pi_get_cv_display(ENCOUNTER.MED_SERVICE_CD) AS MED_SERVICE,
	pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CLASS_CD) AS ENCNTR_TYPE,
	--PRSNL.PERSON_ID AS PROVIDER_ID,
	PRSNL.NAME_FULL_FORMATTED AS PROVIDER,
	pi_get_cv_display(PRSNL.POSITION_CD) AS PROVIDER_POSITION,
	TO_NUMBER(OD_STRENGTHDOSE.OE_FIELD_DISPLAY_VALUE) AS DOSE,
	OD_STRENGTHDOSEUNIT.OE_FIELD_DISPLAY_VALUE AS DOSE_UNIT,
	TO_NUMBER(OD_VOLUMEDOSE.OE_FIELD_DISPLAY_VALUE) AS VOLUME,
	OD_VOLUMEDOSEUNIT.OE_FIELD_DISPLAY_VALUE AS VOLUME_UNIT,
	pi_get_cv_display(FREQUENCY_SCHEDULE.FREQUENCY_CD) AS FREQ,
	OD_SPECINX.OE_FIELD_DISPLAY_VALUE AS SPECIAL_INSTRUCTIONS,
	CASE ORDERS.PRN_IND
		WHEN 1 THEN 'PRN'
		ELSE 'Scheduled'
	END AS PRN,
	OD_PRNINSTRUCTIONS.OE_FIELD_DISPLAY_VALUE AS PRN_INSTRUCTIONS,
	TO_NUMBER(OD_DISPENSEQTY.OE_FIELD_DISPLAY_VALUE) AS DISPENSE_QTY,
	OD_DISPENSEQTYUNIT.OE_FIELD_DISPLAY_VALUE AS DISPENSE_QTY_UNIT,
	TO_NUMBER(OD_DURATION.OE_FIELD_DISPLAY_VALUE) AS DURATION,
	OD_DURATIONUNIT.OE_FIELD_DISPLAY_VALUE AS DURATION_UNIT,
	TO_NUMBER(OD_NBRREFILLS.OE_FIELD_DISPLAY_VALUE) AS NUM_REFILLS
FROM
	ENCOUNTER,
	FREQUENCY_SCHEDULE,
	ORDER_ACTION,
	ORDER_DETAIL OD_DISPENSEQTY,
	ORDER_DETAIL OD_DISPENSEQTYUNIT,
	ORDER_DETAIL OD_DURATION,
	ORDER_DETAIL OD_DURATIONUNIT,
	ORDER_DETAIL OD_DURATIONUNIT,
	ORDER_DETAIL OD_NBRREFILLS,
	ORDER_DETAIL OD_PRNINSTRUCTIONS,
	ORDER_DETAIL OD_SPECINX,
	ORDER_DETAIL OD_STRENGTHDOSE,
	ORDER_DETAIL OD_STRENGTHDOSEUNIT,
	ORDER_DETAIL OD_VOLUMEDOSE,
	ORDER_DETAIL OD_VOLUMEDOSEUNIT,
	ORDERS,
	PI_THERA_CLASS_VIEW,
	PRSNL
WHERE
	PI_THERA_CLASS_VIEW.DRUG_CAT IN ('narcotic analgesic combinations', 'narcotic analgesics')
	AND PI_THERA_CLASS_VIEW.DRUG_CAT_CD = ORDERS.CATALOG_CD
	AND ORDERS.ORIG_ORDER_DT_TM BETWEEN
		--pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), pi_time_zone(2, @Variable('BOUSER'))) 
		--AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
		pi_to_gmt(TRUNC(SYSDATE - 7, 'DAY'), pi_time_zone(2, @Variable('BOUSER')))
		AND pi_to_gmt(TRUNC(SYSDATE, 'DAY') - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
	AND ORDERS.ORIG_ORD_AS_FLAG = 1 -- Prescription/Discharge Order
	AND ORDERS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND ENCOUNTER.LOC_FACILITY_CD IN (
		3310, -- HH HERMANN
		3796, -- HC Childrens
		3821, -- HH Clinics
		3822, -- HH Trans Care
		3823 -- HH Rehab
	)
	AND ORDERS.ORDER_ID = ORDER_ACTION.ORDER_ID
	AND ORDER_ACTION.ACTION_TYPE_CD = 1376 -- Order
	AND ORDER_ACTION.ORDER_PROVIDER_ID = PRSNL.PERSON_ID
	AND ORDERS.FREQUENCY_ID = FREQUENCY_SCHEDULE.FREQUENCY_ID
	AND (
		ORDERS.ORDER_ID = OD_DISPENSEQTY.ORDER_ID(+)
		AND OD_DISPENSEQTY.ACTION_SEQUENCE(+) = 1
		AND OD_DISPENSEQTY.OE_FIELD_MEANING_ID(+) = 2015
	)
	AND (
		ORDERS.ORDER_ID = OD_DISPENSEQTYUNIT.ORDER_ID(+)
		AND OD_DISPENSEQTYUNIT.ACTION_SEQUENCE(+) = 1
		AND OD_DISPENSEQTYUNIT.OE_FIELD_MEANING_ID(+) = 2102
	)
	AND (
		ORDERS.ORDER_ID = OD_DURATION.ORDER_ID(+)
		AND OD_DURATION.ACTION_SEQUENCE(+) = 1
		AND OD_DURATION.OE_FIELD_MEANING_ID(+) = 2061
	)
	AND (
		ORDERS.ORDER_ID = OD_DURATIONUNIT.ORDER_ID(+)
		AND OD_DURATIONUNIT.ACTION_SEQUENCE(+) = 1
		AND OD_DURATIONUNIT.OE_FIELD_MEANING_ID(+) = 2062
	)
	AND (
		ORDERS.ORDER_ID = OD_NBRREFILLS.ORDER_ID(+)
		AND OD_NBRREFILLS.ACTION_SEQUENCE(+) = 1
		AND OD_NBRREFILLS.OE_FIELD_MEANING_ID(+) = 67
	)
	AND (
		ORDERS.ORDER_ID = OD_PRNINSTRUCTIONS.ORDER_ID(+)
		AND OD_PRNINSTRUCTIONS.ACTION_SEQUENCE(+) = 1
		AND OD_PRNINSTRUCTIONS.OE_FIELD_MEANING_ID(+) = 2101
	)
	AND (
		ORDERS.ORDER_ID = OD_SPECINX.ORDER_ID(+)
		AND OD_SPECINX.ACTION_SEQUENCE(+) = 1
		AND OD_SPECINX.OE_FIELD_MEANING_ID(+) = 1103
	)
	AND (
		ORDERS.ORDER_ID = OD_STRENGTHDOSE.ORDER_ID(+)
		AND OD_STRENGTHDOSE.ACTION_SEQUENCE(+) = 1
		AND OD_STRENGTHDOSE.OE_FIELD_MEANING_ID(+) = 2056
	)
	AND (
		ORDERS.ORDER_ID = OD_STRENGTHDOSEUNIT.ORDER_ID(+)
		AND OD_STRENGTHDOSEUNIT.ACTION_SEQUENCE(+) = 1
		AND OD_STRENGTHDOSEUNIT.OE_FIELD_MEANING_ID(+) = 2057
	)
	AND (
		ORDERS.ORDER_ID = OD_VOLUMEDOSE.ORDER_ID(+)
		AND OD_VOLUMEDOSE.ACTION_SEQUENCE(+) = 1
		AND OD_VOLUMEDOSE.OE_FIELD_MEANING_ID(+) = 2058
	)
	AND (
		ORDERS.ORDER_ID = OD_VOLUMEDOSEUNIT.ORDER_ID(+)
		AND OD_VOLUMEDOSEUNIT.ACTION_SEQUENCE(+) = 1
		AND OD_VOLUMEDOSEUNIT.OE_FIELD_MEANING_ID(+) = 2059
	)

WITH DC_RX AS (

), ORD_DETAILS AS (
	SELECT DISTINCT
		ORDER_DETAIL.ORDER_ID,
		ORDER_DETAIL.OE_FIELD_MEANING,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE
	FROM
		DC_RX,
		ORDER_DETAIL
	WHERE
		DC_RX.ORDER_ID = ORDER_DETAIL.ORDER_ID
		AND ORDER_DETAIL.ACTION_SEQUENCE = 1
), ORD_DETAIL_PIVOT AS (
	SELECT * FROM OD
	PIVOT(
		MIN(OE_FIELD_DISPLAY_VALUE) FOR OE_FIELD_MEANING IN (
			'DISPENSEQTY' AS DISPENSE_QTY,
			'DISPENSEQTYUNIT' AS DISPENSE_UNIT,
			'DURATION' AS DURATION,
			'DURATIONUNIT' AS DURATION_UNIT,
			'FREETXTDOSE' AS FREETXT_DOSE,
			'PRNINSTRUCTIONS' AS PRN_INSTR,
			'NBRREFILLS' AS REFILLS,
			'RXROUTE' AS ROUTE,
			'SPECINX' AS SPECIAL_INSTR,
			'STRENGTHDOSE' AS DOSE,
			'STRENGTHDOSEUNIT' AS DOSE_UNIT,
			'VOLUMEDOSE' AS VOLUME,
			'VOLUMEDOSEUNIT' AS VOLUME_UNIT
		)
	)
)
