WITH ICD AS (
	SELECT DISTINCT
		NOMENCLATURE.NOMENCLATURE_ID
	FROM
		NOMENCLATURE
	WHERE
		REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^D57') > 0 
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
), PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.REG_DT_TM,
		ENCOUNTER.DISCH_DT_TM,
		DIAGNOSIS.DIAG_PRIORITY
	FROM
		DIAGNOSIS,
		ENCOUNTER,
		ICD
	WHERE
		ENCOUNTER.DISCH_DT_TM BETWEEN 
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:80),
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				),
				pi_time_zone(1, @Variable('BOUSER'))
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'01/01/1800 23:59:59'}, User:81),
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				),
				pi_time_zone(1, @Variable('BOUSER'))
			)
		AND ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			688523 -- Observation
		)
		AND ENCOUNTER.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab
		)
		AND (
			ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
			AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		)
		AND ICD.NOMENCLATURE_ID = DIAGNOSIS.NOMENCLATURE_ID
), ATTENDINGS AS (
	SELECT 
		PATIENTS.ENCNTR_ID,
		ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID,
		ENCNTR_PRSNL_RELTN.BEG_EFFECTIVE_DT_TM,
		ENCNTR_PRSNL_RELTN.END_EFFECTIVE_DT_TM,
		ENCNTR_PRSNL_RELTN.TRANSACTION_DT_TM
	FROM
		ENCNTR_PRSNL_RELTN,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ENCNTR_PRSNL_RELTN.ENCNTR_ID
		AND ENCNTR_PRSNL_RELTN.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
		AND ENCNTR_PRSNL_RELTN.ACTIVE_IND = 1
)
SELECT
	PATIENTS.ENCNTR_ID AS ENCOUNTER_ID,
	CLINICAL_EVENT.EVENT_ID AS EVENT_ID,
	TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS EVENT_DATETIME,
    (CLINICAL_EVENT.EVENT_END_DT_TM - PATIENTS.REG_DT_TM) * 24 AS ADMIT_EVENT_HRS,
	pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
	CLINICAL_EVENT.RESULT_VAL AS RESULT_VAL,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	pi_get_cv_display(ENCNTR_LOC_HIST.MED_SERVICE_CD) AS MED_SERVICE,
	PRSNL.NAME_FULL_FORMATTED AS ATTENDING
FROM
	ATTENDINGS,
	CLINICAL_EVENT,
	ENCNTR_LOC_HIST,
	PATIENTS,
	PRSNL
WHERE
	PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
	AND CLINICAL_EVENT.EVENT_CLASS_CD IN (
		159, -- NUM
		162 -- TXT
	)
	AND CLINICAL_EVENT.EVENT_CD IN (
		1353917535, -- PCA Clinician Bolus
		1353917564, -- PCA Clinician Bolus Unit
		700103069, -- PCA Concentration
		700103420, -- PCA Continuous Rate Dose
		700103515, -- PCA Demand Dose
		700103573, -- PCA Demand Dose Unit
		1353917859, -- PCA Doses Delivered
		900876112, -- PCA Drug
		802776519, -- PCA Loading Dose
		700103330, -- PCA Lockout Interval (minutes)
		700104137, -- PCA Number of Attempts
		700104271, -- PCA Number of Injections
		900876333, -- PCA Number of Undelivered Attempts
		900876210 -- PCA Total Demands
	)
	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN PATIENTS.REG_DT_TM AND PATIENTS.DISCH_DT_TM
	AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	)
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
	AND CLINICAL_EVENT.ENCNTR_ID = ATTENDINGS.ENCNTR_ID
	AND ATTENDINGS.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	AND ATTENDINGS.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
	AND ATTENDINGS.PRSNL_PERSON_ID = PRSNL.PERSON_ID
