WITH BMI AS (
	SELECT DISTINCT
		ENCNTR_ALIAS.ENCNTR_ID,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS BMI
	FROM
		CLINICAL_EVENT,
		ENCNTR_ALIAS
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND (
			ENCNTR_ALIAS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
			AND CLINICAL_EVENT.EVENT_CD = 119838802 -- Body Mass Index
			AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		)
	GROUP BY
		ENCNTR_ALIAS.ENCNTR_ID
)

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	ENCOUNTER.DISCH_DT_TM - ENCOUNTER.REG_DT_TM AS LOS,
    TRUNC(((pi_from_gmt(ENCOUNTER.REG_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) - PERSON.BIRTH_DT_TM) / 365.25, 0) AS AGE,
	pi_get_cv_display(PERSON.RACE_CD) AS RACE,
	pi_get_cv_display(PERSON.SEX_CD) AS SEX,
	BMI.BMI AS BMI,
	pi_get_cv_display(ENCOUNTER.DISCH_DISPOSITION_CD) AS DISCH_DISPOSITION
FROM
	BMI,
	ENCNTR_ALIAS,
	ENCOUNTER,
	PERSON
WHERE
    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND (
		ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.ACTIVE_IND = 1
	)
	AND (
        ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
        AND PERSON.ACTIVE_IND = 1		
	)
	AND ENCNTR_ALIAS.ENCNTR_ID = BMI.ENCNTR_ID
	
