SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	CLINICAL_EVENT.EVENT_ID AS EVENT_ID,
	TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS EVENT_DATETIME,
	CV_EVENT.DISPLAY AS EVENT,
	CLINICAL_EVENT.RESULT_VAL AS RESULT,
	CV_RESULT_UNITS.DISPLAY AS RESULT_UNIT
FROM
    CLINICAL_EVENT,
    CODE_VALUE CV_EVENT,
    CODE_VALUE CV_RESULT_UNITS,
	ENCNTR_ALIAS
WHERE
    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
	AND ENCNTR_ALIAS.END_EFFECTIVE_DT_TM > SYSDATE
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619
    AND (
        ENCNTR_ALIAS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
    	AND CLINICAL_EVENT.EVENT_CD IN (326948035, 134392449, 134392425, 1474731502, 3102077393, 2884038207)
	    AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
        AND CLINICAL_EVENT.EVENT_CD = CV_EVENT.CODE_VALUE
        AND CLINICAL_EVENT.RESULT_UNITS_CD = CV_RESULT_UNITS.CODE_VALUE
    )
