SELECT DISTINCT
	ENCNTR_ALIAS.ENCNTR_ID AS ENCOUNTER_ID,
	SURGICAL_CASE.SURG_CASE_ID AS SURG_CASE_ID,
	TO_CHAR(pi_from_gmt(SURGICAL_CASE.SURG_START_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS SURGERY_START_DATETIME,
	TO_CHAR(pi_from_gmt(SURGICAL_CASE.SURG_STOP_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS SURGERY_STOP_DATETIME,
	SURGICAL_CASE.SURG_START_DT_TM - ENCOUNTER.REG_DT_TM AS PREOP_LOS,
	ENCOUNTER.DISCH_DT_TM - SURGICAL_CASE.SURG_STOP_DT_TM AS POSTOP_LOS,
	CASE SURG_CASE_PROCEDURE.PRIMARY_PROC_IND
		WHEN 1 THEN 'TRUE'
		ELSE 'FALSE'
	END AS PRIMARY_PROCEDURE,
	pi_get_cv_display(SURG_CASE_PROCEDURE.SURG_PROC_CD) AS SURGERY
FROM
	ENCNTR_ALIAS,
	ENCOUNTER,
	SURGICAL_CASE,
	SURG_CASE_PROCEDURE
WHERE
    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
	AND (
		ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.ACTIVE_IND = 1
	)
    AND (
	    ENCNTR_ALIAS.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID
    	AND SURGICAL_CASE.ACTIVE_IND = 1
    	AND SURGICAL_CASE.SURG_AREA_CD > 0
    )
    AND (
		SURGICAL_CASE.SURG_CASE_ID = SURG_CASE_PROCEDURE.SURG_CASE_ID
		AND SURG_CASE_PROCEDURE.ACTIVE_IND = 1
    )
