SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	SURGICAL_CASE.SURG_CASE_ID AS SURG_CASE_ID,
	TO_CHAR(pi_from_gmt(SURGICAL_CASE.SURG_START_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS SURGERY_START_DATETIME,
	TO_CHAR(pi_from_gmt(SURGICAL_CASE.SURG_STOP_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS SURGERY_STOP_DATETIME,
	CASE SURG_CASE_PROCEDURE.PRIMARY_PROC_IND
		WHEN 1 THEN 'TRUE'
		ELSE 'FALSE'
	END AS PRIMARY_PROCEDURE,
	CV_SURG_PROC.DISPLAY AS SURGERY
FROM
	CODE_VALUE CV_SURG_PROC,
	ENCNTR_ALIAS,
	SURGICAL_CASE,
	SURG_CASE_PROCEDURE
WHERE
    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
	AND ENCNTR_ALIAS.END_EFFECTIVE_DT_TM > SYSDATE
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619
    AND (
	    ENCNTR_ALIAS.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID
    	AND SURGICAL_CASE.ACTIVE_IND = 1
    	AND SURGICAL_CASE.SURG_AREA_CD > 0
    )
    AND (
		SURGICAL_CASE.SURG_CASE_ID = SURG_CASE_PROCEDURE.SURG_CASE_ID
		AND SURG_CASE_PROCEDURE.ACTIVE_IND = 1
		AND SURG_CASE_PROCEDURE.SURG_PROC_CD = CV_SURG_PROC.CODE_VALUE
    )
