---
title: "Acetminophen Orders in Day Surgery Patients"
author: "Brian Gulbis, PharmD, BCPS"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(themebg)

df_orders <- read_excel("../data/raw/apap_dsu_orders.xlsx") %>%
    rename_all(str_to_lower) %>%
    mutate_at("anesth_start_datetime", ~coalesce(., surg_start_datetime)) %>%
    mutate_at("anesth_stop_datetime", ~coalesce(., surg_stop_datetime))

# df_doses <- read_excel("../data/raw/apap_dsu_doses.xlsx") %>%
#     rename_all(str_to_lower) %>%
#     mutate(
#         orig_order_id = if_else(
#             template_order_id == 0, 
#             order_id, 
#             template_order_id
#         )
#     ) %>%
#     select(-template_order_id, -order_id)
# 
# df_surg <- read_excel("../data/raw/test_surgeries.xlsx") %>%
#     rename_all(str_to_lower)
# 
# df <- df_orders %>%
#     left_join(df_doses, by = c("encntr_id", "order_id" = "orig_order_id")) %>%
#     filter(route != "PYXIS") %>%
#     inner_join(df_surg, by = "encntr_id")

first_orders <- df_orders %>%
    arrange(encntr_id, order_datetime) %>%
    distinct(encntr_id, surg_case_id, .keep_all = TRUE) %>%
    mutate(
        po_dose = order_route %in% c("PO", "GT", "JT"),
        order_prior_day = floor_date(order_datetime, "days") < floor_date(anesth_start_datetime, "days"),
        po_prior_surg = order_datetime < anesth_start_datetime & po_dose
    )

po_before <- df_orders %>%
    filter(
        order_datetime < anesth_start_datetime,
        order_route %in% c("PO", "GT", "JT")
    ) %>%
    arrange(encntr_id, surg_case_id, event_id) %>%
    distinct(encntr_id, surg_case_id, .keep_all = TRUE) %>%
    mutate(
        same_day = floor_date(order_datetime, "days") == 
            floor_date(anesth_start_datetime, "days"),
        given_before = if_else(dose_datetime < anesth_start_datetime, TRUE, FALSE, FALSE),
        given = !is.na(event_id),
        order_to_surg_min = difftime(
            anesth_start_datetime,
            order_datetime, 
            units = "mins"
        )
    ) %>%
    mutate_at("order_to_surg_min", as.numeric)

ordered_not_given <- po_before %>%
    filter(!given)

day_of_not_given <- ordered_not_given %>%
    filter(same_day) 

no_po_order <- df_orders %>%
    anti_join(po_before, by = c("encntr_id", "surg_case_id")) %>%
    arrange(encntr_id, surg_case_id, event_id) %>%
    distinct(encntr_id, surg_case_id, .keep_all = TRUE) %>%
    mutate(
        iv_dose = order_route %in% c("IV", "IVPB"),
        same_day = floor_date(dose_datetime, "days") == 
            floor_date(anesth_stop_datetime, "days"),
        iv_timing = case_when(
            iv_dose & dose_datetime >= anesth_stop_datetime & same_day ~ "post-op",
            iv_dose & dose_datetime >= anesth_start_datetime & same_day ~ "intra-op",
            TRUE ~ "none"
        )
    )

fmt_table <- function(.df, .cap, .cols) {
    knitr::kable(
        x = .df,
        caption = .cap,
        col.names = .cols,
        booktabs = TRUE,
        digits = 0
    )
}
```

```{r}
first_orders %>%
    count(po_prior_surg) %>%
    mutate(pct = n / nrow(first_orders) * 100) %>%
    fmt_table(
        "How many patients had oral acetaminophen ordered before surgery?",
        c("PO orderd before surgery", "No. patients", "% patients")
    )

```

```{r}
first_orders %>%
    count(order_prior_day) %>%
    mutate(pct = n / nrow(first_orders) * 100) %>%
    fmt_table(
        "Among all patients, how many had an order (IV or PO) placed before admission?",
        c("Ordered before admit", "No. patients", "% patients")
    )

```

```{r}
po_before %>%
    count(given_before) %>%
    mutate(pct = n / nrow(po_before) * 100) %>%
    fmt_table(
        "Among those with orders prior to surgery, how many received an oral dose before surgery?",
        c("Dose give before surgery", "No. patients", "% patients")
    )

```

```{r}
ordered_not_given %>%
    count(same_day) %>%
    mutate(pct = n / nrow(ordered_not_given) * 100) %>%
    fmt_table(
        "Among those with orders prior to surgery but the dose was not given, how many had orders placed the same day?",
        c("Ordered day of surgery", "No. patients", "% patients")
    )
```

```{r}
day_of_not_given %>%
    summarize_at(
        "order_to_surg_min",
        list(
            mean = mean,
            sd = sd,
            median = median,
            iqr = IQR
        )
    ) %>%
    fmt_table(
        "Among those with orders placed prior to surgery on the day of surgery and not given, how many minutes prior to surgery was the order placed?",
        c("Mean", "SD", "Median", "IQR")
    )
```

```{r, fig.cap="How many minutes prior to surgery was the order placed in patients who were and were not given a dose?"}
po_before %>%
    filter(same_day) %>%
    ggplot(aes(x = given, y = order_to_surg_min)) +
    geom_boxplot() +
    ggtitle("Time prior to surgery when order was placed") +
    xlab("Dose was given") +
    ylab("Minutes prior to surgery") +
    theme_bg()
```

```{r}
no_po_order %>%
    count(iv_timing) %>%
    mutate(pct = n / nrow(no_po_order) * 100) %>%
    fmt_table(
        "When oral was not ordered before surgery, how many patients received IV acetaminophen during surgery?",
        c("IV given during surgery", "No. patients", "% patients")
    )
```

```{r}
iv_doses <- df_orders %>%
    filter(
        !is.na(dose_datetime),
        order_route %in% c("IV", "IVPB"),
        admin_nurse_unit == "HH DSU"
    ) %>%
    mutate(
        same_day = floor_date(dose_datetime, "days") == 
            floor_date(anesth_stop_datetime, "days"),
        iv_timing = case_when(
            dose_datetime < anesth_start_datetime & same_day ~ "Pre-op",
            dose_datetime >= anesth_stop_datetime & same_day ~ "Post-op",
            dose_datetime < anesth_start_datetime ~ "Prior to day of surgery",
            dose_datetime >= anesth_stop_datetime ~ "POD 1 or later",
            TRUE ~ "Intra-op"
        )
    )

iv_doses %>%
    count(iv_timing, sort = TRUE) %>%
    mutate(pct = n / nrow(iv_doses) * 100) %>%
    fmt_table(
        "Timing of IV doses in Day Surgery Unit",
        c("IV dose given", "No. doses", "% doses")
    )
```


```{r, eval=FALSE}
df_orders %>%
    filter(
        !is.na(dose_datetime),
        order_route %in% c("IV", "IVPB"),
        admin_nurse_unit == "HH DSU"
    ) %>%
    count(dose_month)
```
