---
title: "Opiod Stewardship"
author: "Brian Gulbis, PharmD, BCPS"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(themebg)

file_groups <- list.files("../data/tidy", recursive = TRUE) %>%
    str_remove_all("\\.Rds") %>%
    str_remove_all(".*/") %>%
    unique()

files <- file_groups %>%
    map(
        .f = ~list.files(
            path = "../data/tidy", 
            pattern = .x, 
            recursive = TRUE, 
            full.names = TRUE
        )
    ) %>%
    map(~map_dfr(.x, read_rds))

names(files) <- file_groups

x <- list2env(files, .GlobalEnv)

rm(files, file_groups)

data_mme <- data_mme_int_patient %>%
    bind_rows(data_mme_cont, data_mme_pca) %>%
    filter(mme.iv > 0) %>%
    group_by(millennium.id, data.month) %>%
    summarize_at("mme.iv", sum, na.rm = TRUE) %>%
    left_join(
        data_los_month[c(
            "millennium.id", 
            "data.month", 
            "los.month",
            "service.dc"
        )], 
        by = c("millennium.id", "data.month")
    ) %>%
    mutate_at(
        "los.month",
        funs(coalesce(., 1))
    ) %>%
    mutate_at(
        "los.month",
        funs(if_else(. < 1, ceiling(.), .))
    ) %>%
    mutate(total.day = mme.iv / los.month)
    
data_mme_iv <- data_mme_int_patient %>%
    filter(mme.iv > 0,
           route.group == "IV") %>%
    group_by(millennium.id, data.month) %>%
    summarize_at("mme.iv", sum, na.rm = TRUE) %>%
    left_join(
        data_los_month[c(
            "millennium.id", 
            "data.month", 
            "los.month",
            "service.dc"
        )], 
        by = c("millennium.id", "data.month")
    ) %>%
    mutate_at(
        "los.month",
        funs(coalesce(., 1))
    ) %>%
    mutate_at(
        "los.month",
        funs(if_else(. < 1, ceiling(.), .))
    ) %>%
    mutate(total.day = mme.iv / los.month)
    
```

```{r, fig.height=8, fig.cap="Total MME per patient per day by service line on discharge. Outliers above 100 MME per day are not displayed. The height of the box represents the number of patients on each service line."}

medians_mme <- data_mme %>%
    group_by(service.dc) %>%
    summarize_at("total.day", median, na.rm = TRUE) %>%
    arrange(desc(total.day)) %>%
    mutate_at("service.dc", as_factor)

data_mme %>%
    group_by(millennium.id) %>%
    mutate_at("service.dc", factor, levels = levels(medians_mme$service.dc)) %>%
    mutate_at("service.dc", fct_rev) %>%
    ggplot(aes(x = service.dc, y = total.day)) +
    geom_boxplot(varwidth = TRUE) +
    xlab(NULL) +
    ylab("MME per patient per day") +
    coord_flip(ylim = c(0, 100)) +
    theme_bg()

```

```{r, fig.height=8, fig.cap="Total MME per patient per day of IV opiods by service line on discharge. Outliers above 50 MME per day are not displayed. The height of the box represents the number of patients on each service line."}

medians_mme_iv <- data_mme_iv %>%
    group_by(service.dc) %>%
    summarize_at("total.day", median, na.rm = TRUE) %>%
    arrange(desc(total.day)) %>%
    mutate_at("service.dc", as_factor)

data_mme_iv %>%
    group_by(millennium.id) %>%
    mutate_at("service.dc", factor, levels = levels(medians_mme_iv$service.dc)) %>%
    mutate_at("service.dc", fct_rev) %>%
    ggplot(aes(x = service.dc, y = total.day)) +
    geom_boxplot(varwidth = TRUE) +
    xlab(NULL) +
    ylab("MME per patient per day") +
    coord_flip(ylim = c(0, 50)) +
    theme_bg()
```

```{r, fig.height=8, fig.cap="Total MME per patient per day by attending. The top 50 attendings by median MME per day are displayed. Outliers above 100 MME per day are not displayed."}
df_md <- data_mme_int_md %>%
    group_by(millennium.id, attending, los.md) %>%
    summarize_at("mme.iv", sum, na.rm = TRUE) %>%
    mutate(total.day = mme.iv / los.md) 

median_md <- df_md %>%
    group_by(attending) %>%
    summarize_at("total.day", median, na.rm = TRUE) %>%
    arrange(desc(total.day)) %>%
    mutate_at("attending", as_factor)

df_md %>%
    ungroup() %>%
    mutate_at("attending", factor, levels = levels(median_md$attending)) %>%
    mutate_at("attending", fct_lump, n = 50) %>%
    mutate_at("attending", fct_rev) %>%
    ggplot(aes(x = attending, y = total.day)) +
    geom_boxplot() +
    xlab(NULL) +
    ylab("MME per patient per day") +
    coord_flip(ylim = c(0, 100)) +
    theme_bg()

```

```{r, fig.height=8, fig.cap="Total MME per patient per day of IV opiods by attending. The top 50 attendings by median MME per day are displayed. Outliers above 100 MME per day are not displayed."}
df_md_iv <- data_mme_int_md %>%
    filter(route.group == "IV") %>%
    group_by(millennium.id, attending, los.md) %>%
    summarize_at("mme.iv", sum, na.rm = TRUE) %>%
    mutate(total.day = mme.iv / los.md) 

median_md_iv <- df_md_iv %>%
    group_by(attending) %>%
    summarize_at("total.day", median, na.rm = TRUE) %>%
    arrange(desc(total.day)) %>%
    mutate_at("attending", as_factor)

df_md_iv %>%
    ungroup() %>%
    mutate_at("attending", factor, levels = levels(median_md_iv$attending)) %>%
    mutate_at("attending", fct_lump, n = 50) %>%
    mutate_at("attending", fct_rev) %>%
    ggplot(aes(x = attending, y = total.day)) +
    geom_boxplot() +
    xlab(NULL) +
    ylab("MME per patient per day") +
    coord_flip(ylim = c(0, 100)) +
    theme_bg()

```

```{r, fig.height=8, fig.cap="MME per patient dispensed by ED provider. Darker bars indicate more prescriptions were written by the provider."}
data_rx_ed %>%
    add_count(order.provider) %>%
    group_by(order.provider, n) %>%
    summarize_at("mme.iv.dispense", sum) %>%
    mutate(mme.pt = mme.iv.dispense / n) %>%
    arrange(desc(mme.pt)) %>%
    ungroup() %>%
    mutate_at("order.provider", as_factor) %>%
    mutate_at("order.provider", fct_rev) %>%
    ggplot(aes(x = order.provider, y = mme.pt)) +
    geom_bar(aes(fill = n), stat = "identity") +
    xlab(NULL) +
    ylab("MME per patient") +
    scale_fill_gradient("Patients (n)", low = "#bdbdbd", high = "#252525") +
    coord_flip() +
    theme_bg()
```

